version: "3.9"
services:
  isc-dhcp-server:
    image: "graphenx/isc-dhcp-server"
    container_name: cntnr-isc-dhcp-pxeboot

    deploy:
      labels:
        isc-dhcp-server.container.usage: "isc-dhcp containerized server for assigning IPv4 addresses"

    environment:
        ENV_DHCP_IF: eth1

    stdin_open: true
    tty: yes
    command: ["/usr/sbin/dhcpd", "-4", "-f", "-d", "--no-pid", "-cf", "/etc/dhcp/dhcpd.conf"]

    ports:
      - "10.172.100.253:67:67/udp"

    volumes:
      - ./volumes/dhcpd.conf:/etc/dhcp/dhcpd.conf

    network_mode: "host"
    #networks:
      #- net-isc-dhcp

      # meter volumen

#networks:
#  net-isc-dhcp: {}
